# Dockerfile for build up the image
FROM python:3.8

RUN echo "init anki-sync-server"
ADD ankisyncd /app/ankisyncd
ADD utils /app/utils
ADD ankisyncctl.py /app/ankisyncctl.py
ADD requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install -r requirements.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com
# RUN pip3 install -r requirements.txt

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

EXPOSE 27701
CMD ["python", "-m", "ankisyncd"]